"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-09-26 08:23:30.473638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('supplier', 'customer', name='partner_type'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partners'))
    )
    op.create_table('uoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uoms')),
    sa.UniqueConstraint('name', name=op.f('uq_uoms_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('manager', 'staff', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('code', name=op.f('uq_warehouses_code')),
    sa.UniqueConstraint('name', name=op.f('uq_warehouses_name'))
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('internal', 'vendor', 'customer', 'adjustment', name='location_type'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_locations_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('warehouse_id', 'name', name='uq_locations_warehouse_id_name')
    )
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_resets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_resets'))
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories')),
    sa.ForeignKeyConstraint(['uom_id'], ['uoms.id'], name=op.f('fk_products_uom_id_uoms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('receipt', 'delivery', 'internal', 'adjustment', name='operation_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'waiting', 'ready', 'done', 'canceled', name='operation_status'), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('source_location_id', sa.Integer(), nullable=False),
    sa.Column('dest_location_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('source_location_id <> dest_location_id', name=op.f('ck_operations_source_dest_different')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_operations_created_by_users')),
    sa.ForeignKeyConstraint(['dest_location_id'], ['locations.id'], name=op.f('fk_operations_dest_location_id_locations')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_operations_partner_id_partners')),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], name=op.f('fk_operations_source_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations')),
    sa.UniqueConstraint('reference', name=op.f('uq_operations_reference'))
    )
    op.create_table('reorder_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('max_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.CheckConstraint('min_qty >= 0 AND min_qty <= max_qty', name=op.f('ck_reorder_rules_min_qty_within_range')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_reorder_rules_product_id_products')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_reorder_rules_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reorder_rules')),
    sa.UniqueConstraint('product_id', 'warehouse_id', name='uq_reorder_rules_product_id_warehouse_id')
    )
    op.create_table('stock_quants',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_stock_quants_quantity_non_negative')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_stock_quants_location_id_locations')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_quants_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'location_id', name=op.f('pk_stock_quants'))
    )
    op.create_table('operation_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_operation_lines_quantity_non_negative')),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_operation_lines_operation_id_operations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_operation_lines_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_lines')),
    sa.UniqueConstraint('operation_id', 'product_id', name='uq_operation_lines_operation_id_product_id')
    )
    op.create_table('stock_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('done_by', sa.Integer(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_stock_moves_quantity_positive')),
    sa.ForeignKeyConstraint(['done_by'], ['users.id'], name=op.f('fk_stock_moves_done_by_users')),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], name=op.f('fk_stock_moves_from_location_id_locations')),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_stock_moves_operation_id_operations')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_moves_product_id_products')),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], name=op.f('fk_stock_moves_to_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_moves'))
    )
    op.create_index('ix_operations_type_status', 'operations', ['type', 'status'])
    op.create_index('ix_stock_moves_product_id_done_at', 'stock_moves', ['product_id', 'done_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_moves_product_id_done_at', table_name='stock_moves')
    op.drop_index('ix_operations_type_status', table_name='operations')
    op.drop_table('stock_moves')
    op.drop_table('operation_lines')
    op.drop_table('stock_quants')
    op.drop_table('reorder_rules')
    op.drop_table('operations')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    op.drop_table('password_resets')
    op.drop_table('locations')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('uoms')
    op.drop_table('partners')
    op.drop_table('categories')
    # ### end Alembic commands ###
